spring.application.name=smart-digital-notepad

spring.datasource.url=jdbc:mysql://localhost:3306/smart_notepad
spring.datasource.username=root
spring.datasource.password=Punisher-2026

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.open-in-view=false

server.port=8080

# ==========================================
# FILE UPLOAD SETTINGS
# ==========================================

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

# ===============================
# FILE UPLOAD SETTINGS
# ===============================

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

server.tomcat.max-http-form-post-size=50MB
server.tomcat.max-swallow-size=-1